version: '3.8'
services:
  miu-wap-server:
    container_name: miu-wap-server-container
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

